name: Update GitHub Activity

on:
  schedule:
    - cron: "* * 1 * *"

jobs:
  update-readme:
    name: Update this repo's README with latest GitHub activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
